language: python
python:
        - "3.5"
sudo: false
services: mongodb
dist: trusty
pre-install:
        - pip install virtualenv
        - virtualenv create venv
        - . venv/bin/activate
install:
        - pip install -r requirements.txt
        - ./setup.py build
script: nosetests
